apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: snowplow
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/snowplow
    version: "0.30.249"
